### ISSUE TITLE
Octicons Syntax not showing in tooltip

### ISSUE THREAD

**Issue by tjohnsonhvac** [actboy168/vscode-tasks#15]
![image](https://user-images.githubusercontent.com/36667609/79581761-e3981280-8098-11ea-9db0-54ecae635839.png)

I checked your source code and the example is in the tooltip, but for some reason it doesnt show in vscode tooltip..

**Comment by actboy168** [comment]
Octicons only support use in labels.

**Comment by tjohnsonhvac** [comment]
I realize that. I was commenting on the tooltip that your extension generates when you hover over the “label” key in settings.json file. Line 3 is missing the syntax example. I had to go into your code in the repo to find out that the correct syntax is $().

**Comment by actboy168** [comment]
Tooltip will support icons after 1.59.
