### ISSUE TITLE
Keyboard shortcuts stoped working for Tasks

### ISSUE THREAD

**Issue by IvanRublev** [actboy168/vscode-tasks#17]
Keybindings were set to run taskboy168.task.X commands.

After update to VSCode 1.45.0 pressing a set keybinding causes a 'command actboy168.task.X' not found error.

How it's possible to fix this?

The tasks configuration file was used [tasks.json.zip](https://github.com/actboy168/vscode-tasks/files/4627088/tasks.json.zip)

```
About VSCode
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
```

<img width="607" alt="image" src="https://user-images.githubusercontent.com/5757941/81913864-d5beaa00-95d0-11ea-9c02-378b33821741.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5757941/81913825-c93a5180-95d0-11ea-901e-99b12a260e8a.png">

**Comment by actboy168** [comment]
`actboy168.task.X` is used in tasks0.4 or lower. After tasks0.5, only `actboy168.run-task` was used. It may be because you still have low-level tasks or VSCode did not clean it up properly.

**Comment by IvanRublev** [comment]
Sorry, I mean X not literally, it can be 0,1,2,3... Please, have a look at the second screensot in the issue description.

**Comment by IvanRublev** [comment]
What is the proper way to attach a keyboard shortcut to a task in tasks0.5?

**Comment by actboy168** [comment]
After a84f0419e2b88b6cc8563ee18c7492b597a3937d, you can do it to it: 

1. Open the keybindings.json file from the Command Palette (Ctrl+Shift+P) with the Preferences: Open Keyboard Shortcuts (JSON) command.
2. Add
``` json
[
    {
        "key": "ctrl+shift+z",
        "command": "actboy168.run-task",
        "args": 1
    }
]
```
This is equivalent to the previous `actboy168.task.0` .

**Comment by IvanRublev** [comment]
Thanks a lot it works and that is amazing 🤩
