### ISSUE TITLE
Hide certain tasks

### ISSUE THREAD

**Issue by bpatram** [actboy168/vscode-tasks#2]
Is there a way to disable the status bar button for certain tasks? I have quite a few tasks on my project but really only want quick access to a select few.

**Comment by actboy168** [comment]
Now you can hide a task like this

```json
        {
            "label": "task",
            "options": {
                "statusbar" : "hide",
            }
        },
```

**Comment by bpatram** [comment]
This is great! Thank you for the quick update!!
