### ISSUE TITLE
Extension settings not available

### ISSUE THREAD

**Issue by rccoleman** [actboy168/vscode-tasks#22]
At some point recently the extension settings for this extension seem to have disappeared and are no longer viewable or modifiable.  I see the same behavior on code-server and on a native MacOS installation - I can see the settings that the extension intends to make available in the "Feature Contributions" section in the addon page, but clicking the cog on the extension and selecting "Extension Settings" brings up nothing (search is actually "@ext:actboy168.tasks".  Same result if I go into Settings and manually search for "tasks".  Other extensions chosen at random, such as [this](https://github.com/mbolaric/vscode-tasks-panel) properly expose their settings.

**Comment by rccoleman** [comment]
Looks like adding the following to the configuration definition fixes it:

```
            "title": "vscode-tasks",
```

**Comment by actboy168** [comment]
I cannot reproduce it. Adding a title is also good, but I want it to be `Tasks` instead of `vscode-tasks`.

**Comment by rccoleman** [comment]
Weird.  I wonder if it was some left over cruft from an older installation, but it was happening on both my MacOS install and with a vscode-server as part of my Home Assistant installation.  When I uninstall the extension, restart VSCode, and re-install from the Marketplace, the settings are coming up now.  So somehow adding the title and reloading from a local .vsix seems to have fixed it, but building and loading .vsix files of earlier versions first didn't fix it.

**Comment by rccoleman** [comment]
It looks like just uninstalled and reinstalling the extension doesn't remove the directory or configuration from the .vscode/extensions directory.  If I uninstall the extension, delete that directory, and reinstall 0.6.0 from the Marketplace, I again get "No Settings Found" when hitting the cog and selecting "Extension Settings":

<img width="994" alt="Screen Shot 2020-08-09 at 9 35 12 PM" src="https://user-images.githubusercontent.com/860888/89752262-85989c00-da88-11ea-9fb2-88aa2fc122d7.png">

vs. when it works:

<img width="999" alt="Screen Shot 2020-08-09 at 9 38 15 PM" src="https://user-images.githubusercontent.com/860888/89752299-b1b41d00-da88-11ea-8519-221a35d8e88b.png">

**Comment by actboy168** [comment]
It may be a bug in VSCode.

**Comment by rccoleman** [comment]
Could be.  It used to work, and I only noticed the issue when I started seeing missing tasks in the status bar and I couldn't access the settings to increase the limit from 6.

**Comment by rccoleman** [comment]
Filed an issue against the main project: https://github.com/microsoft/vscode/issues/104442

**Comment by rccoleman** [comment]
Looks like it's being fixed via https://github.com/microsoft/vscode/commit/67243326c1aabab30c7500e1fb4fd5a19e385e13.  I'll close this issue now.
