### ISSUE TITLE
Duplicate Buttons

### ISSUE THREAD

**Issue by zifik** [actboy168/vscode-tasks#25]
This extension is not properly clearing existing tasks buttons during load.

When doing remote development, there are situations where VSCode loses connection and asks to "reload window".  When this occurs, the task buttons are duplicated. If the window reloads again, then there are 3x the number of task buttons. 

Version: v0.7.0
VSCode: 1.50.1

**Comment by actboy168** [comment]
Every refresh will clear all statusbar first. There should be no duplicate statusbar unless VSCode does not release the statusbar correctly.

**Comment by zifik** [comment]
Then perhaps the fault lies with the remote development extension and how it reconnects/reloads.

**Comment by joao-p-marques** [comment]
This is also happening to me. I am not using remote development, but from time to time some buttons are duplicated, and I have to reload the VSCode window to revert back to the correct settings.

**Comment by actboy168** [comment]
I did not find the error, but I added an optimization. Now the extension will reuse the created statusbar. This may solve part of the problem.

**Comment by viperet** [comment]
![Extension: Tasks](https://user-images.githubusercontent.com/725651/108356576-fa495180-71f4-11eb-846c-551d02fac003.png)
Unfortunately, it still happens to me, and it's very annoying.

It's a local workspace, just opened it and got many duplicated buttons. "Developer: Reload Window" not solved this issue, but closing and reopening the workspace solved it.

**Comment by sandym** [comment]
I see that almost everyday, not using remote development. Editing and re-saving the tasks.json reset the status bar. This is my only grief with this very useful extension.

**Comment by sandym** [comment]
I've create a pull request with something that seems to fix the problem. Haven't seen duplicates on the 2 machines I deployed that change.
