### ISSUE TITLE
Running certain tasks fail with error "Tasks to execute must include an execution"

### ISSUE THREAD

**Issue by frankkahl** [actboy168/vscode-tasks#26]
First of all thank you for writing this really great extension.

After upgrading to the newest VSCode 1.52.1 running the Task "refresh submodules" from the status bar using your extension (version 0.8.0) fails with the error message:
"Tasks to execute must include an execution"

I suspect it is an issue with their task extension. The task itself has no "command" property but is a sequence of other tasks. Running it via the "Terminal -> Run Task..." Menu is successful.

Below you find the used tasks.json in a ZIP archive

Have a merry christmas,

Frank
--------------------------------------------------------------------------------------------------------------------------------------
[tasks.zip](https://github.com/actboy168/vscode-tasks/files/5721292/tasks.zip)

**Comment by actboy168** [comment]
This is a VSCode bug. It should be fixed in 1.53.
https://github.com/microsoft/vscode/issues/112545

**Comment by frankkahl** [comment]
Thank you very much for your quick response. This VSCode bug slipped my google search.
In the meanwhile I circumvented the bug by adding
"command": ":",
to the task.
