### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by alexzshl** [actboy168/vscode-tasks#28]
1. Add dynamic styles to the button by listening to the start/stop event of the task: `vscode.tasks.onDidStartTask`, `$(sync~spin)`

    complex tasks dependencies :
    ![dependents](https://user-images.githubusercontent.com/39125296/105045810-480e5500-5aa3-11eb-8211-173eca64b19d.gif)

2. Add examples for schema statubar-label to view all icons (300+ icons) from codicon library. I can provide it later, if you think this is useful
    ![image](https://user-images.githubusercontent.com/39125296/105043762-e3ea9180-5aa0-11eb-8abd-7d3bfc6c1bdf.png)

3. I have noticed that some users use tasks configured with `depends Order` and `dependsOn`. Maybe they want the subtasks to be displayed dynamically. The subtasks will not be displayed, when the main task is running, the subtasks will temporarily appears and then disappears

**Comment by actboy168** [comment]
1. Adding the running status to the label will change the position of part of the statusbar. This is the reason why I did not add this feature.
2. It looks like a good feature, but it has nothing to do with this extension. This extension just solves the problem of displaying the task on the statusbar to make it easier to start a task. Not how to write a task.This should be a problem solved by another extension or VSCode.
3. Same as 1. In addition, I don't want to turn this extension into a complicated task manager, it just allows you to start a task more simply.

**Comment by alexzshl** [comment]
1. Do you mean that temporarily changing the value of the label will cause the position to change?
    ```statusBar.text = statusBar.text + " $(sync~spin)";```
