### ISSUE TITLE
No Tasks visible - v0.8.1 with VSCode 1.53.2

### ISSUE THREAD

**Issue by dragonnn** [actboy168/vscode-tasks#31]
Hi,
I all my projects the extension stopped working, it worked fine before with all my tasks.json
The extension is v0.8.1 and using Visual Studio Code 1.53.2 on Linux.
I tried reverting to different versions but it didn't work. 
What I found out that starting with a new user-data-dir fixes the problem, but I want to keep my settings... and when I create a new dir and sync my settings into it stops working.
Any idea what could help to fix that?

**Comment by actboy168** [comment]
Did you set `tasks.statusbar.default.hide` to true?

**Comment by dragonnn** [comment]
Nope, I already tried switching it in both options and it doesn't change anything.

**Comment by actboy168** [comment]
Can you find out which setting is causing the extension to not work?

**Comment by dragonnn** [comment]
Hmmm i just copied and paste my settings into a new data-dir and now it is working -_-.
No idea why it was broken when I used the sync my settings option....
