### ISSUE TITLE
star (*) in filepattern 

### ISSUE THREAD

**Issue by kraabrsg** [actboy168/vscode-tasks#33]
Hi,
thank you for this nice little extension.
It would be nice to add support for filepatterns like 
`
*.txt 
`  
Patterns like "xxx*.*" are working nicely...

Thanks!

**Comment by actboy168** [comment]
The current syntax is regex, although I also prefer glob.

**Comment by kraabrsg** [comment]
Ahh, i should have tried that first, thanks!
