### ISSUE TITLE
Publish in Open VSX

### ISSUE THREAD

**Issue by yajo** [actboy168/vscode-tasks#34]
open-vsx.org is an alternative extensions store that is fully open. Allows using extensions in VSCodium or Gitpod for example.

Would you mind publishing this extension there? See https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by actboy168** [comment]
Sounds great, I will investigate it.

**Comment by philoserf** [comment]
https://github.com/HaaLeo/publish-vscode-extension

**Comment by yajo** [comment]
There's one less cool alternative: https://open-vsx.org/extension/cnshenj/vscode-task-manager

Still missing this though. 😿

**Comment by yajo** [comment]
FTR I asked and they packaged this downstream: https://github.com/open-vsx/publish-extensions/pull/585

Still it would be better if it's published from here upstream, so current issue still makes sense.

**Comment by actboy168** [comment]
Done.
