### ISSUE TITLE
Extensions of non-standard types not showing

### ISSUE THREAD

**Issue by migmit** [actboy168/vscode-tasks#35]
For me, the default task is of "haxe" type, and it was not showing. I solved the problem by changing this line:
https://github.com/actboy168/vscode-tasks/blob/f0daa2a235edb65a740e3787d46e10f012f071b4/extension.js#L270
to `if (!task.definition.id) {`. Not sure if it would work for others.

**Comment by actboy168** [comment]
You can open a pull request.
