### ISSUE TITLE
Class constructor Yt cannot be invoked without 'new'

### ISSUE THREAD

**Issue by antfp** [actboy168/vscode-tasks#37]
Have this error when loading the extension: Class constructor Yt cannot be invoked without 'new', which prevents  the display of the tasks bar. Traced back the error to line 285 of extension.js : 285 --> return vscode.ThemeColor(color);
Changed it to 285 --> return new vscode.ThemeColor(color); and now everything works fine.

Computer: Apple M1 MacBook Pro. OS: macOS Ventura

**Comment by actboy168** [comment]
Thanks.
