### ISSUE TITLE
How to assign a keyboard shortcut for a specific task

### ISSUE THREAD

**Issue by kcvinker** [actboy168/vscode-tasks#38]
Hi, thank you for this wonderful extension. How to assign a keyboard shortcut for a specific task ? I have 4 tasks which I created with this extension. But one among them is the most used. So I've decided to assign a shortcut key for that. Thanks in advance.

**Comment by actboy168** [comment]
https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks

**Comment by actboy168** [comment]
```json
{
  "key": "ctrl+h",
  "command": "workbench.action.tasks.runTask",
  "args": "Run Python Code"
}
```

**Comment by kcvinker** [comment]
Thanks a lot. Let me try this. :)
