### ISSUE TITLE
VS Code 1.76 - no Tasks visible

### ISSUE THREAD

**Issue by Parchbrot** [actboy168/vscode-tasks#39]
hi,
after VS Code update 1.76 no task icons are visible.
Tasks v.0.11.1, Window 10, VS Code 1.76.0

**Comment by actboy168** [comment]
What is your tasks.json?

**Comment by Parchbrot** [comment]
we have integrated the tasks configuration into our workspace file:

{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		// set window title
		"window.title": "CE | ${activeEditorShort} | ${activeFolderLong}",
		"workbench.colorCustomizations": {
		},
	},
	"extensions": {
		"recommendations": [
			"actboy168.tasks",
			"aaron-bond.better-comments",
			"christian-kohler.path-intellisense",
			"codezombiech.gitignore",
			"2gua.rainbow-brackets",
			"DavidAnson.vscode-markdownlint",
			"DotJoshJohnson.xml",
			"ms-dotnettools.csharp",
			"ms-vscode.powershell",
			"ms-vscode.vs-keybindings",
			"naco-siren.gradle-language",
			"PKief.material-icon-theme",
			"redhat.fabric8-analytics",
			"redhat.java",
			"redhat.vscode-yaml",
			"VisualStudioExptTeam.vscodeintellicode",
			"vscjava.vscode-java-debug",
			"vscjava.vscode-java-dependency",
			"vscjava.vscode-java-test",
			"zhuangtongfa.material-theme"
		],
	},
	"tasks": {
		"version": "2.0.0",
		"echoCommand": true,
		"clear": true,
		"tasks": [{
			"label": "NPM_Install",
			"type": "shell",
			"command": [
				"npm install",
			],
			"problemMatcher": [],
			"options": {
				"statusbar": {
					"label": "$(play) NPM Install",
				},
				"shell": {
					"executable": "C:\\Windows\\system32\\cmd.exe",
					"args": [
						"/d",
						"/c"
					]
				}
			}
		},
		{
			"label": "NPM_InstallElectron",
			"type": "shell",
			"command": [
				"cd node_modules/electron",
				"&",
				"node install.js",
			],
			"problemMatcher": [],
			"options": {
				"statusbar": {
					"label": "$(play) NPM Install Electron",
				},
				"shell": {
					"executable": "C:\\Windows\\system32\\cmd.exe",
					"args": [
						"/d",
						"/c"
					]
				}
			}
		},
		{
			"label": "NPM_Build",
			"type": "shell",
			"command": [
				"npm run build",
			],
			"problemMatcher": [],
			"options": {
				"statusbar": {
					"label": "$(play) NPM Run Build",
				},
				"shell": {
					"executable": "C:\\Windows\\system32\\cmd.exe",
					"args": [
						"/d",
						"/c"
					]
				}
			}
		},
		{
			"label": "NPM_RunWatch",
			"type": "shell",
			"command": [
				"npm run watch",
			],
			"problemMatcher": [],
			"options": {
				"statusbar": {
					"label": "$(play) NPM Run Watch",
				},
				"shell": {
					"executable": "C:\\Windows\\system32\\cmd.exe",
					"args": [
						"/d",
						"/c"
					]
				}
			}
		},
		{
			"label": "NPM_Start",
			"type": "shell",
			"command": [
				"npm start",
			],
			"problemMatcher": [],
			"options": {
				"statusbar": {
					"label": "$(play) NPM Start",
				},
				"shell": {
					"executable": "C:\\Windows\\system32\\cmd.exe",
					"args": [
						"/d",
						"/c"
					]
				}
			}
		}
	],
	}
}

**Comment by actboy168** [comment]
Try your config file, and I can see the statusbar.

**Comment by damienlsq** [comment]
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "xxx",
			"detail": "",
			"command": "grunt reloadRelease"
		},
	]
}

**Comment by actboy168** [comment]
I can't reproduce it.

You can check if the settings `tasks.statusbar.default.hide` is true.

**Comment by Parchbrot** [comment]
no hide attribute

**Comment by Parchbrot** [comment]
update: I saw, that the icons will be shown after changing the content of the launch.json independent of the content. after restart the task icons are gone again

**Comment by Parchbrot** [comment]
update2: I guess it is a VS Code issue. I merged my launch.json and the workspace file. After each modify and save the icons are visible. After a restart they are gone...

**Comment by actboy168** [comment]
May be related to https://github.com/microsoft/vscode/issues/176006.

**Comment by damienlsq** [comment]
today vscode up to 1.76.1, and I try install tasks version 0.11.1， can show tasks icons, but the newest version 0.12.1，still gone

**Comment by GaspardRig** [comment]
Hi,
I got the same issue, no tasks are visible in status bar in Tasks version 0.12.1, but work in 0.12.0

Vscode :

> Version: 1.76.1 (system setup)
> Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
> Date: 2023-03-08T16:32:00.131Z
> Electron: 19.1.11
> Chromium: 102.0.5005.196
> Node.js: 16.14.2
> V8: 10.2.154.26-electron.0
> OS: Windows_NT x64 10.0.22621
> Sandboxed: No

**Comment by actboy168** [comment]
> Hi, I got the same issue, no tasks are visible in status bar in Tasks version 0.12.1, but work in 0.12.0
> 

@GaspardRig What is your tasks.json?

**Comment by GaspardRig** [comment]
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "meson",
            "args": [
                "compile",
                "-C",
                "build/"
            ],
            "icon": {
                "id": "tools"
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true,
                "revealProblems": "onProblem",
                "clear": false
            }
        },
        {
            "label": "Clean",
            "command": "meson",
            "args": [
                "compile",
                "--clean",
                "-C",
                "build/"
            ],
            "icon": {
                "id": "trash"
            },
            "presentation": {
                "close": true
            }
        },
        {
            "label": "CPPCheck",
            "command": "cppcheck",
            "args": ["--enable=all", "--error-exitcode=1","./drivers/", "./include/", "./tst/"],
            "icon": {"id": "check-all"},
            "presentation": {
                "revealProblems": "onProblem",
                "clear": true,
            }
        },
        {
            "label": "Build Doc",
            "command": "make",
            "args": [
                "html"
            ],
            "icon": {
                "id": "book"
            },
            "options": {
                "cwd": "${workspaceFolder}/doc"
            }
        },
        {
            "label": "Build PDF",
            "command": "make",
            "args": [
                "latexpdf"
            ],
            "icon": {
                "id": "book"
            },
            "options": {
                "cwd": "${workspaceFolder}/doc"
            }
        },
        {
            "label": "Coding Style",
            "command": "python",
            "args": [
                "./scripts/uncrustify.py"
            ],
            "icon": {
                "id": "pencil"
            },
            "options": {
                "cwd": "${workspaceFolder}"
            }
        }
    ]
}
`

**Comment by GaspardRig** [comment]
Fix with 0.12.2, thanks :)

**Comment by Parchbrot** [comment]
no change on my side. task icons just appear if I modify and save the json file

**Comment by actboy168** [comment]
@Parchbrot  Can VSCode 1.76.1 solve your problem?

**Comment by Parchbrot** [comment]
VS code has updated automatically and no changes with Tasks extension update...

**Comment by actboy168** [comment]
@Parchbrot You can disable other extensions and see if it works.

**Comment by CircuitHawk** [comment]
Same issue on my end. Start VS Code, no tasks icons. However icons will re-appear under the following conditions:

1) Go to settings and check then uncheck "Tasks > Statusbar > Default: Hide"
2) Make a change in tasks.json and re-save
3) Disable Tasks extension, reload VS Code, then re-enable Tasks

Running VS Code 1.76.1 and Tasks 0.12.2. Windows 10. Thanks for the support!

**Comment by johndatserakis** [comment]
Had the same issue.

Updated my `tasks[0].options.statusbar.hide` to `false`. It was not specifically set before.

It's showing properly now. Perhaps the `hide` default got toggled somehow in the latest VSCode update. I've never personally touched it.

**Comment by kcvinker** [comment]
I have the same issue. No items are visible in status bar. This is my task.json.

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Odin App",
            "options": {
                "statusbar": {
                    "hide": false
                }
            },
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\Odin\\Winforms",
                "-run",
                "odin run",
                "app.odin",
                "-file"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            }
        },
        {
            "label": "DebugWing",
            "options": {
                "statusbar": {
                    // "hide": false
                }
            },
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\D Lang\\Wings",
                "-run",
                "dmd -debug -i -run app.d"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            }
        },

        {
            "label": "Copy Wings Folder",
            "options": {
                "statusbar": {
                    "hide": true
                }
            },
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-run",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\D Lang\\Wings Helper\\wings_copier.exe"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            }
        },
        {
            "label": "Run Python App",
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "c:\\Users\\kcvin\\OneDrive\\Programming\\Python\\PyForms",
                "-run",
                "python",
                "app.py"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "Run Autoit App",
            "options": {
                "statusbar": {
                    "hide": true
                }
            },
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-run",
                "C:\\Program Files (x86)\\AutoIt3\\SciTE\\AutoIt3Wrapper\\AutoIt3Wrapper.au3",
                "/run",
                "/prod",
                "/ErrStdOut",
                "/in",
                "c:\\Users\\kcvin\\OneDrive\\Programming\\Autoit Projects\\Windowing Experiments\\app.au3"
            ],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            }
        },

        {
            "label": "Run_C3",
            "options": {
                "statusbar": {
                    // "hide": false
                }
            },
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\C3\\CForms\\cforms",
                "-run",
                "c3c run cforms"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            }
        },

        {
            "label": "Run Lua_App",
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\Lua\\LuaForms",
                "-run",
                "luajit",
                "app.lua"
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "problemMatcher": []
        },

        {
            "label": "Run Nelua",
            "type": "process",
            "command": "ConEmu64",
            "args": [
                "-Dir",
                "C:\\Users\\kcvin\\OneDrive\\Programming\\Nelua\\Nforms",
                "-run",
                "nelua", "--cache-dir", "bin", "app.nelua",
            ],
            "presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
            "options": {
                "statusbar": {
                    "color" : "#22C1D6"
                }
            },
            "problemMatcher": []
        },
    ],
    "statusbar.default.hide": true,
    "statusbar.limit": 8,

}
```

**Comment by actboy168** [comment]
@pp244 What is your tasks.json?

**Comment by actboy168** [comment]
@pp244  I can't reproduce it. You mean this tasks.json works in 0.12.3 but not in 0.13?

Can you try disabling other extensions?

**Comment by kcvinker** [comment]
@pp244, How disable all extensions ? How did you do that ?

**Comment by actboy168** [comment]
@pp244 0.13.1 already fixed.

**Comment by kcvinker** [comment]
@actboy168 Yes, it worked after disabled all other extensions.

**Comment by actboy168** [comment]
@kcvinker Can you find out which extension makes tasks invisible?

**Comment by Parchbrot** [comment]
after VS Code update 1.76.2 and Tasks update 0.13.1 the icons now are visisble directly after VS Code Start.
Thx much for support!
👍
