### ISSUE TITLE
名称label错乱

### ISSUE THREAD

**Issue by xygengcn** [actboy168/vscode-tasks#47]
多个任务的时候点击其他任务的名称都会变成第一个

以前没有出现，最近出现的

<img width="498" alt="截屏2023-06-21 21 27 34" src="https://github.com/actboy168/vscode-tasks/assets/35959814/a39ae66a-1965-4d38-aceb-8247d4c5f1f2">

**Comment by actboy168** [comment]
请提供你的tasks.json

**Comment by xygengcn** [comment]
> 

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run-Core",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-core/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Gateway",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-gateway/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Public",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-public/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Blog",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-blog/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Api",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-api/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Store",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-store/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Socket",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-socket/"
            },
            "problemMatcher": []
        },
        {
            "label": "Run-Maxmind",
            "type": "shell",
            "command": "yarn dev",
            "options": {
                "cwd": "${workspaceFolder}/services/quark-service-maxmind/"
            },
            "problemMatcher": []
        },
    ]
}

**Comment by actboy168** [comment]
我无法重现

**Comment by xygengcn** [comment]
> 我无法重现

版本，两个项目都是这样

版本: 1.79.2 (Universal)
提交: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
日期: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by xygengcn** [comment]
今天更新vscode又恢复了

版本: 1.80.0 (Universal)
提交: 660393deaaa6d1996740ff4880f1bad43768c814
日期: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
Chromium: 21893604
Node.js: 108.0.5359.215
V8: 16.17.1
OS: 10.8.168.25-electron.0
