### ISSUE TITLE
Some tasks not appearing in status bar after 0.15.2

### ISSUE THREAD

**Issue by ArcanoxDragon** [actboy168/vscode-tasks#48]
After updating to 0.15.2, some of my tasks are not appearing in the status bar. 0.15.3 doesn't fix the problem. If I downgrade to 0.15.1, the tasks all appear correctly.

I have created a Gist that reproduces the issue: https://gist.github.com/ArcanoxDragon/3b8b3f9b2fb2684160d37ce4ff1a22c8
The `tasks.json` file from the Gist needs to go in a `.vscode` folder next to `package.json`, of course.

On 0.15.1, both tasks show up in the status bar, but in 0.15.2 and 0.15.3, only the "Yarn Install" task appears. It seems like [this change](https://github.com/actboy168/vscode-tasks/commit/d579f6f0e4287b878cfabe822fe000037285c81e#diff-19a9a3efb94bf1b84229bda71ab0ef5badcdbf34ba3a0c9e4152a82c569a21e6L313-R313) is responsible; `matchComposite` returns `false` for the NPM task that doesn't show up.

**Comment by sr-tream** [comment]
Similar bug. But all work on 0.15.2 for me and do not show any tasks on 0.15.3
