### ISSUE TITLE
Tasks are always visible

### ISSUE THREAD

**Issue by sersanchus** [actboy168/vscode-tasks#5]
With last vscode update (1.35.1) and version 0.2.2 of this extension installed, tasks are always visible on status bar regardless of the "hide" setting en tasks.json
Anyone else with the same problem?

**Comment by actboy168** [comment]
Please provide your tasks.json.

**Comment by sersanchus** [comment]
This one, for example:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "task",
            "type": "shell",
            "command": "b"
        },
        {
            "label": "hidden task",
            "type": "shell",
            "command": "b1",
            "windows": {
                "command": "b2"
            },
            "options": {
                "statusbar": "hide"
            }
        }
    ]
}
```

I have come to a small conclusion, which is that the problem is on the "windows" command specialization. Maybe the "statusbar" option is not parsed in that case.
