### ISSUE TITLE
Tasks with same exact command string are treated as the same?

### ISSUE THREAD

**Issue by sersanchus** [actboy168/vscode-tasks#6]
I have noticed that tasks with same command string can cause extrange problems. In a tasks.json like the next one the two tasks are hidden whe only one has the hide attribute actived:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "task",
            "type": "shell",
            "command": "b1"
        },
        {
            "label": "hidden task",
            "type": "shell",
            "command": "b1",
            "options": {
                "statusbar": "hide"
            }
        }
    ]
}
```

**Comment by actboy168** [comment]
microsoft/vscode#67095

Because of the lack of VSCode's task api support, I can only associate tasks.json and task objects myself.

I added label as part of the hash, but it may still not solve all the problems.

**Comment by sersanchus** [comment]
Thanks! For me the label solution works as expected.
