### ISSUE TITLE
Taskbar ordering conflicts with git

### ISSUE THREAD

**Issue by MarkusRodler** [actboy168/vscode-tasks#8]
Some days ago I noticed that the ordering of tasks in the taskbar is wrong:
![image](https://user-images.githubusercontent.com/14873906/60806882-7a3bb880-a184-11e9-9fbf-88c8f29308c3.png)

The git branch and refresh button should be the first entries.
Can you modify the position? It seems the position of the git entries depends on the time the Tasks plugin needs to load

**Comment by actboy168** [comment]
This is a VSCode bug that has been fixed in 1.37 and may be fixed in 1.36.1.

**Comment by MarkusRodler** [comment]
Thanks for the information. Keep up the great work!

**Comment by fheinicke** [comment]
I just updated to VS Code 1.36.1 where this issue is supposedly fixed (see issue microsoft/vscode#76561) by the PR microsoft/vscode#76598. However the issue is still coming up for me when using this extension.

![grafik](https://user-images.githubusercontent.com/27764426/61050175-9fc7fc80-a3e6-11e9-8f93-cdb6b9687fc8.png)

**Comment by actboy168** [comment]
I think this is two bugs.

**Comment by infinnie** [comment]
https://github.com/actboy168/vscode-tasks/blob/master/js/extension.js#L115
如果 priority 为 50 的话那和 Source Control 的 priority 是一样的，但是根据此修复
https://github.com/microsoft/vscode/pull/76598/files#diff-c8a07f370ae15468fbaf8367a502ced0R128
似乎该修复之前的问题即在 Source Control 和 Problems 具有相同的优先级—50 (https://github.com/microsoft/vscode/pull/76598#issuecomment-508482343)
优先级 10000, 50 & 49 看来都已经被内置使用了。你可能有必要防止与内建状态栏项的冲突。

**Comment by fheinicke** [comment]
The issue seems to have been fixed by VS Code 1.37.0 or 1.37.1 like @actboy168 noted - I cannot reproduce it anymore.
@MarkusRodler can you confirm?

**Comment by MarkusRodler** [comment]
Yes I can confirm that it is fixed now aufter the update.
