### ISSUE TITLE
Add extension-option to hide all tasks by default and enable conditionally

### ISSUE THREAD

**Issue by nifr** [actboy168/vscode-tasks#9]
First of all thank you for this wonderful extension. I use it a lot!

The extension currently provides the option to hide a single task like this:

    "options": {
      "statusbar": "hide"
    }

As - in my current project - I have a lot of tasks in my `tasks.json` it's quite some work to disable them all.

It would be great to have a settings-option for the default visibility and be able to just enable single tasks conditionally in the task-options.

I'd suggest introducing a new task-option (to maintain backwards compatibility) `showInStatusBar` (boolean) for **tasks.json** ...

    "options": {
      "showInStatusBar": true
    }

... and  a "global' option `tasks.showInStatusbar` inside **settings.json**.

    "tasks.showInStatusBar": {
      "default": false
    }

I might contribute such functionality in case you're interested.

Thanks again for your idea and work on this extension. Greatly appreciated!

**Comment by actboy168** [comment]
This is a good idea. I would be very grateful if you could provide this feature.
